import streamlit as st
from predict import predict_text

st.set_page_config(page_title="AI Authorship Detector", page_icon="🤖", layout="centered")

st.title("AI Authorship Detector")
st.write("Detect whether a piece of text is written by a human or generated by AI.")

user_text = st.text_area("Enter text to analyze:", height=200)

if st.button("Analyze"):
    if user_text.strip() == "":
        st.warning("Please enter some text.")
    else:
        prediction, confidence_scores = predict_text(user_text)

        st.subheader("Prediction")
        st.success(f"This text is predicted as: **{prediction.upper()}**")

        st.subheader("Confidence Scores")
        for label, score in confidence_scores.items():
            st.write(f"**{label}**: {score:.2%}")